[tool.poetry]
name = "variance"
version = "0.1.0"
description = ""
authors = ["louisChiffre"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
setuptools = "^70.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
